CREATE TABLE `minions` (
`id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE KEY,
`name` VARCHAR(45) NOT NULL,
`age` INT NOT NULL
) ENGINE=InnoDB;

CREATE TABLE `towns` (
`town_id` INT NOT NULL PRIMARY KEY AUTO_INCREMENT UNIQUE KEY,
`name` VARCHAR(45) NOT NULL
) ENGINE=InnoDB;